<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam"><?php echo $this->adminNavigation ?>

        <div class="title">Index of: menu items</div>

        <?php echo $this->messages() ?>

        <?php if ($this->allowCreateItem) : ?>
        <div class="actions">
            <img src="/images/icons/add.png" alt="Add icon" />
            <a class="link-button" href="<?php echo $this->url('item', ['action' => 'create'], ['query' => ['from' => 'menu', 'provisionalTo' => 'Menu', 'provisionalBeneathMenuItemId' => 0]]); ?>">Create new at top level</a>
        </div>
        <?php endif; ?>

        </div><!-- End top area -->

        <div id="stage"><!-- Start stage area -->

            <table class="table">
                <thead>
                    <tr>
                        <th>&nbsp;</th>
                        <th colspan="10">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($this->menuItems) : ?>
                    <?php echo $this->partialLoop('boxspaced/cms-menu-module/menu/menu-item.phtml', $this->menuItems) ?>
                    <?php else : ?>
                    <tr class="odd"><td width="100%">Empty result set</td><td colspan="10">&nbsp;</td></tr>
                    <?php endif; ?>
                </tbody>
            </table>

        </div><!-- End stage area -->

    </body>
</html>
