
        <div class="row">
            <div class="col-md-12">

                <h1>Menu</h1>

                <div class="panel panel-default">

                    <div class="panel-heading clearfix">
                        <?php if ($this->allowCreateItem) : ?>
                        <a class="btn btn-success pull-left" href="<?php echo $this->url('item', ['action' => 'create'], ['query' => ['from' => 'menu', 'provisionalTo' => 'Menu', 'provisionalBeneathMenuItemId' => 0]]); ?>">Create new at top level</a>
                        <?php endif; ?>
                    </div>

                    <table class="table">
                        <tbody>
                            <?php if ($this->menuItems) : ?>
                            <?php echo $this->partialLoop('boxspaced/cms-menu-module/menu/menu-item.phtml', $this->menuItems) ?>
                            <?php else : ?>
                            <tr class="odd"><td width="100%">Empty result set</td><td colspan="10">&nbsp;</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
