<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Idea Store CMS</title>
        <link rel="stylesheet" href="/css/site.css" media="screen" />
        <style>
            body {
                padding: 1em;
            }
        </style>
    </head>
    <body>
        <div class="well">
            <h3>Menu</h3>
            <?php echo $this->navigation('Navigation\Main')->menu()->renderMenu(null, array(
                'ulClass' => 'sitemap',
            )); ?>
        </div>
        <div class="well">
            <h3>Standalone</h3>
            <ul>
            <?php foreach ($this->standaloneItems as $item) : ?>
                <li><a href="<?php echo $this->url('content', ['slug' => $item->name]); ?>"><?php echo $this->escapeHtml($item->navText) ?></a></li>
            <?php endforeach; ?>
            </ul>
        </div>
        <script src="/js/site.js"></script>
        <script type="text/javascript" >
            $(document).ready(function() {
               $('a').click(function(e) {
                   e.preventDefault();
                   var href = $(this).attr('href');
                   var dialog = window.opener.CKEDITOR.dialog.getCurrent();
                   dialog.setValueOf('info', 'url', href);
                   dialog.setValueOf('info', 'protocol', '');
                   window.close();
                   return false;
               });
            });
        </script>
    </body>
</html>
